//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibArcachon
{
    using System;
    using System.Collections.Generic;
    
    public partial class Epreuve
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Epreuve()
        {
            this.Tps = new HashSet<Tps>();
        }
    
        public int Id_Epreuve { get; set; }
        public string Point_Depart { get; set; }
        public string Point_Arrive { get; set; }
        public System.DateTime Heure_Depart { get; set; }
        public System.DateTime Heure_Arrive_theorique { get; set; }
        public int idcourse { get; set; }
    
        public virtual Course Course { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tps> Tps { get; set; }
    }
}
