//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibArcachon
{
    using System;
    using System.Collections.Generic;
    
    public partial class Membre
    {
        public int Id_Membre { get; set; }
        public string Nom { get; set; }
        public string Prenom { get; set; }
        public string login { get; set; }
        public string Mdp { get; set; }
        public string Email { get; set; }
        public int Tel { get; set; }
        public string Poste { get; set; }
    }
}
