//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibArcachon
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ProjetArcachonEntities : DbContext
    {
        public ProjetArcachonEntities()
            : base("name=ProjetArcachonEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Course> Course { get; set; }
        public virtual DbSet<Entreprise> Entreprise { get; set; }
        public virtual DbSet<Epreuve> Epreuve { get; set; }
        public virtual DbSet<ListePenalite> ListePenalite { get; set; }
        public virtual DbSet<Membre> Membre { get; set; }
        public virtual DbSet<Penalite> Penalite { get; set; }
        public virtual DbSet<Personne> Personne { get; set; }
        public virtual DbSet<Sponsoring> Sponsoring { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Temps> Temps { get; set; }
        public virtual DbSet<TypeDeClasse> TypeDeClasse { get; set; }
        public virtual DbSet<Voilier> Voilier { get; set; }
        public virtual DbSet<VoilierInscrit> VoilierInscrit { get; set; }
    }
}
