//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibArcachon
{
    using System;
    using System.Collections.Generic;
    
    public partial class Penalite
    {
        public int Id_Penalite { get; set; }
        public int VoilierInscrit { get; set; }
        public int idepreuve { get; set; }
        public string Latitude { get; set; }
        public string Logitude { get; set; }
        public System.TimeSpan Duree { get; set; }
        public int idlistepenalite { get; set; }
    
        public virtual ListePenalite ListePenalite { get; set; }
        public virtual VoilierInscrit VoilierInscrit1 { get; set; }
    }
}
