//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibArcachon
{
    using System;
    using System.Collections.Generic;
    
    public partial class Personne
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Personne()
        {
            this.VoilierInscrit = new HashSet<VoilierInscrit>();
            this.VoilierInscrit1 = new HashSet<VoilierInscrit>();
            this.VoilierInscrit2 = new HashSet<VoilierInscrit>();
        }
    
        public int Id_Personne { get; set; }
        public string Nom { get; set; }
        public string Prenom { get; set; }
        public string Numero_Club { get; set; }
        public string Numero_Licence { get; set; }
        public string Sexe { get; set; }
        public string idNumeroInscription { get; set; }
        public System.DateTime Date_naissance { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VoilierInscrit> VoilierInscrit { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VoilierInscrit> VoilierInscrit1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VoilierInscrit> VoilierInscrit2 { get; set; }
    }
}
