//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibArcachon
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tps
    {
        public int ID_TEMPS { get; set; }
        public int IDepreuve { get; set; }
        public int IDvoilierInscrit { get; set; }
        public Nullable<System.TimeSpan> Temps { get; set; }
    
        public virtual Epreuve Epreuve { get; set; }
        public virtual VoilierInscrit VoilierInscrit { get; set; }
    }
}
